### ISSUE TITLE
WireGuard object doesn't clean up open sockets on drop

### ISSUE THREAD

**Issue by K900** [ArgosyLabs/wgnlpy#1]
Doing something like

```python
while True:
     WireGuard().add_peer(...)
```

Results in eventually running out of FDs, as `WireGuard` keeps a reference to a Netlink socket internally which isn't closed when the `WireGuard` object is dropped. 

I know a better option would be to lift the socket creation out of the loop, but the behavior is still unexpected and should probably be fixed. The best solution would be to support the context manager protocol for `WireGuard`, but explicitly closing the socket in `__del__` should also help common use cases.

**Comment by pallas** [comment]
Thanks, fixed in v0.1.1

**Comment by K900** [comment]
Thank you!
